version: '3.9'

services:
  rustdesk-hbbs:
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r rustdesk.app.levell.ch:21117
    networks:
      - rustdesk
    depends_on:
      - rustdesk-hbbr

  rustdesk-hbbr:
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    networks:
      - rustdesk
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
   rustdesk: